---
- include: debian.yml
  when: ansible_os_family == 'Debian'

- name: Create a shared directory
  file:
    path: /home/{{ user }}/shared/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
    state: directory

- name: Create a systemd default mount to user directory
  template:
    src: templates/home-shared.mount.j2
    dest: /etc/systemd/system/home-shared.mount
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  vars:
    user: "{{ user }}"

- name: Create a systemd default mount to user directory
  template:
    src: templates/cifs.j2
    dest: /root/.cifs
  vars:
    user: "{{ user }}"

- name: Just force systemd to reread configs
  systemd: daemon_reload=yes

- name: Create an entry in the fstab to automatically deploy
  lineinfile:
    path: /etc/fstab
    line: "//10.0.2.4/qemu         /home/{{ user }}/shared/  cifs    uid=1000,credentials=/root/.cifs,x-systemd.automount,noperm 0 0"
